openapi: 3.0.3
info:
  title: Safety Law Helper API
  version: "v5.2"
servers:
  - url: https://YOUR-RENDER-DOMAIN
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
                  uptime: { type: number }
                  version: { type: string }
                  count: { type: integer }
  /search:
    get:
      summary: Search laws by keyword
      parameters:
        - in: query
          name: keyword
          required: true
          schema: { type: string }
        - in: query
          name: exact
          schema: { type: boolean }
        - in: query
          name: page
          schema: { type: integer }
        - in: query
          name: page_size
          schema: { type: integer }
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
  /answer:
    get:
      summary: Natural language question → Answer
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Answer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerResponse'
components:
  schemas:
    SearchItem:
      type: object
      properties:
        lawId: { type: string }
        lawTitle: { type: string }
        unitType: { type: string }
        unitNo: { type: string }
        title: { type: string }
        textPlain: { type: string }
        textHtml: { type: string }
        enactedAt: { type: string }
        amendedAt: { type: string }
        sourceUrl:
          type: string
          description: "law.go.kr/법령/{법령ID} (내부 식별용, 실제 열람은 정식 뷰어 안내)"
    SearchResponse:
      type: object
      properties:
        total: { type: integer }
        page: { type: integer }
        page_size: { type: integer }
        items:
          type: array
          items: { $ref: '#/components/schemas/SearchItem' }
    AnswerResponse:
      type: object
      properties:
        ok: { type: boolean }
        content: { type: string }
        disclaimer: { type: string }
