openapi: 3.0.1
info:
  title: SafetyLawGPT API
  version: "1.1.0"
servers:
  - url: /

paths:
  /healthz:
    get:
      operationId: healthz
      summary: Health check & load stats
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  ts:
                    type: string
                  laws_loaded:
                    type: integer
                  sheets:
                    type: integer
                  yaml:
                    type: integer

  /reload:
    get:
      operationId: reload
      summary: Reload laws from Sheets + YAML
      responses:
        "200":
          description: Reloaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  reloaded:
                    type: integer
                  sheets:
                    type: integer
                  yaml:
                    type: integer

  /search:
    get:
      operationId: search
      summary: Local keyword search across loaded laws
      parameters:
        - in: query
          name: keyword
          required: true
          schema:
            type: string
            minLength: 1
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 50
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        law_id:
                          type: string
                        law_name:
                          type: string
                        article_no:
                          type: string
                        title:
                          type: string
                        revision_date:
                          type: string
                        db_synced_at:
                          type: string
                        level:
                          type: string
                          description: act/decree/rule/notice
                          enum: [act, decree, rule, notice]
                        source:
                          type: string

  /answer:
    get:
      operationId: answer
      summary: Compose v5.8 response (근거/본문/면책고지)
      parameters:
        - in: query
          name: keyword
          required: true
          schema:
            type: string
            minLength: 1
        - in: query
          name: role_lock
          description: 역할 잠금 (혼동 방지)
          required: false
          schema:
            type: string
            enum: [안전관리자, 보건관리자, 안전보건총괄책임자, 관리감독자, 안전보건관리담당자, 산업보건의]
        - in: query
          name: include_all_levels
          description: 법·령·규칙·고시까지 다층 근거 출력
          required: false
          schema:
            type: boolean
            default: true
        - in: query
          name: scan_frequency
          description: '반기 1회 이상 등 빈도 전수 스캔 강제 플래그(미지정 시 키워드로 자동 감지)'
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: v5.8 blocks
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  generated_at:
                    type: string
                  legal_basis:
                    type: string
                    description: "[근거] 블록(반말 요약 포함)"
                  middle:
                    type: string
                    description: "(제목 없는 본문) 블록(존댓말)"
                  disclaimer:
                    type: string
                    description: "[면책고지] 블록"
                  markdown:
                    type: string
                    description: "3블록 전체 마크다운"
                  params:
                    type: object
                    properties:
                      role_lock:
                        type: string
                        nullable: true
                      include_all_levels:
                        type: boolean
                      scan_frequency:
                        type: boolean

  /diag:
    get:
      operationId: diag
      summary: Sheets connectivity diagnostics
      responses:
        "200":
          description: OK or error
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
